<a href="https://colab.research.google.com/github/maroqijalil/ai-au-nb/blob/main/numpy_AU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array((1,2,3,4))
print(a)

[1 2 3 4]


In [ ]:
a=np.zeros(1)
print(a)
b=np.ones(10)
print(b)

[0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr=np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [ ]:
a=np.array([(12,33,2,13,4,44), (2,3,2,11,2,1)])
print(a)
print(len(a))
print(len(a[0]))

[[12 33  2 13  4 44]
 [ 2  3  2 11  2  1]]
2
6


In [ ]:
a=np.linspace(0, 2, 11)
print(a)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
a=np.array((1,2,3,4))
print(a+1)
print(a*2)

[2 3 4 5]
[2 4 6 8]


In [ ]:
a=np.array((1,2,3,4))
b=np.array((3,24,35,-2))
print(a+b)
print(a*b)
print(np.sum(a))
print(np.min(a))
print(np.max(a))

[ 4 26 38  2]
[  3  48 105  -8]
10
1
4


In [ ]:
a=np.array((1,2,3,4,3,24,35,-2))
print(a.clip(2,8))
b=np.array([(1,2,3,4,3,24,35,-2), (1,2,3,4)], dtype=object)
print(b)
print(b.shape)
print(b.ndim)

[2 2 3 4 3 8 8 2]
[(1, 2, 3, 4, 3, 24, 35, -2) (1, 2, 3, 4)]
(2,)
1
[1.3681231e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000]


In [ ]:
print(np.empty(5))
b=np.empty((5, 2))
print(b)
print(b.T)

[1.3681231e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# practice 1
a=np.array([np.zeros(6), np.ones(6)], dtype=float)
print(a)
b=np.zeros((6, 7))
print(b)
x=np.array([(1,2), (3,4)])
y=np.array([(5,6), (7,8)])
dotXY=x.dot(y)
print(dotXY)
print(np.min(dotXY))
print(np.max(dotXY))
print(np.average(dotXY))
print(np.mean(dotXY))

[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[19 22]
 [43 50]]
19
50
33.5
33.5
